name: R Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      R_LIBS_USER: ${{ github.workspace }}/r-libs

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libgdal-dev libgeos-dev libproj-dev libudunits2-dev
    
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: ${{ runner.os }}-r-
    
    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("testthat", "mockery", "sf", "dplyr", "tidyr", "devtools"))'
        Rscript -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'
    
    - name: Run tests
      run: |
        Rscript -e 'testthat::test_dir("tests/testthat")'
    
    - name: Generate test coverage report
      run: |
        Rscript -e 'install.packages("covr")'
        Rscript -e 'covr::package_coverage()'
